import Head from 'next/head'
import Banner from '../components/Banner'
import Footer from '../components/Footer'
import Header from '../components/Header'
import Partners from '../components/Partners'
import SmallDesc from '../components/SmallDesc'
import TalkToUs from '../components/TalkToUs'
import Testimonials from '../components/Testimonials'
import TrustedBy from '../components/TrustedBy'

export default function Home() {
  return (
    <div>
      <Head>
        <title>XpertOpt</title>
        <meta charset="utf-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <meta name="description" content="Generated by create next app" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@900&display=swap" rel="stylesheet"/> 
      </Head>

      <Header/>
      <Banner/>
      <TrustedBy/>
      <Partners/>
      <SmallDesc/>
      <Testimonials/>
      <TalkToUs/>
      <Footer/>
    </div>
  )
}
